### ISSUE TITLE
KeyError: 'color' in all replays I've tested

### ISSUE THREAD

**Issue by ghost** [enzanki-ars/rocket-league-minimap-generator#47]
Using launch option --render_all and getting the following output for this sample replay, but also occurs with all replays I've tested that are < 6 months old

```
Traceback (most recent call last):
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cameron\Desktop\DiscordBot\ReplayParser\replayanalysis\rocketleaguereplayanalysis\main.py", line 171, in <module>
    main()
  File "C:\Users\Cameron\Desktop\DiscordBot\ReplayParser\replayanalysis\rocketleaguereplayanalysis\main.py", line 166, in main
    team_info, video_prefix)
  File "C:\Users\Cameron\Desktop\DiscordBot\ReplayParser\replayanalysis\rocketleaguereplayanalysis\render\do_render.py", line 53, in render
    filter_type=render_cmd['filter'])
  File "C:\Users\Cameron\Desktop\DiscordBot\ReplayParser\replayanalysis\rocketleaguereplayanalysis\render\ffmpeg_cmd.py", line 72, in create_ffmpeg_cmd_files_from_path
    all_data)
  File "C:\Users\Cameron\Desktop\DiscordBot\ReplayParser\replayanalysis\rocketleaguereplayanalysis\render\ffmpeg_cmd.py", line 70, in <lambda>
    curr_val = functools.reduce(lambda d, key: d[key],
KeyError: 'color'
```

[65904B664DCDF1FB9CB7CBA7C3B8686C.zip](https://github.com/enzanki-ars/rocket-league-replay-analysis/files/1719256/65904B664DCDF1FB9CB7CBA7C3B8686C.zip)

**Comment by enzanki-ars** [comment]
I am pretty sure that this issue is fixed now.  While it works on my end, I have seen code fail on other's ends, so let me know if it works on your end.  It seems like you are running git master, so I trust that you are able to run the newest code, but let me know if I should upload a new version of the exe.
